export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR'
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'

export const FETCH_TRANSACTIONS_REQUEST = 'FETCH_TRANSACTIONS_REQUEST'
export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTIONS_SUCCESS'
export const FETCH_TRANSACTIONS_ERROR = 'FETCH_TRANSACTIONS_ERROR'

export const FETCH_ANIMALS_REQUEST = 'FETCH_ANIMALS_REQUEST'
export const FETCH_ANIMALS_SUCCESS = 'FETCH_ANIMALS_SUCCESS'
export const FETCH_ANIMALS_ERROR = 'FETCH_ANIMALS_ERROR'

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
