export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR'
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'

export const FETCH_TRANSACTION_REQUEST = 'FETCH_TRANSACTION_REQUEST'
export const FETCH_TRANSACTION_SUCCESS = 'FETCH_TRANSACTION_SUCCESS'
export const FETCH_TRANSACTION_ERROR = 'FETCH_TRANSACTION_ERROR'

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
